### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by FullMetalMaster** [AbraXator/MoreSnifferFlowers#1]
[crash-2023-07-05_17.09.08-client.txt](https://github.com/AbraXator/MoreSnifferFlowers/files/11962139/crash-2023-07-05_17.09.08-client.txt)
Got this crash on load.

**Comment by AbraXator** [comment]
Hey, this crash isn't related to our mod. It¨s cause by another mod called Sniffer Plus. Sou you'll need to open an issue there, because we can't do anything about it.
