### ISSUE TITLE
Amber needs heavy rework

### ISSUE THREAD

**Issue by moonfather1** [AbraXator/MoreSnifferFlowers#10]
to keep the mod (i like it) i had to make a datapack forbidding ambush seeds from being dug up.

single ambush bush completely obsoletes any sniffers you have around - those orange cubes grow stupidly fast and give you everything a sniffer does (and more - but i still had to disable those).

**Comment by Nikdo53** [comment]
Hey so good news, all of the stuff you reported is already fixed/reworked in the new update that should be released later this week 😎😎😎(though the neoforge might take a bit longer) but thanks for reporting anyway
