### ISSUE TITLE
Unable to log into server

### ISSUE THREAD

**Issue by mxnmnm** [AbraXator/MoreSnifferFlowers#11]
The 1.4 and 1.4.1 updates have made it so I can't log on my server.

Here is the client log: https://gist.github.com/mxnmnm/a5fd9aebfb43d2fe258714d7f78f726b

**Comment by mxnmnm** [comment]
![2024-05-08_19 31 50](https://github.com/AbraXator/MoreSnifferFlowers/assets/8508976/84c202c2-ba9a-461f-b618-8d9990ca6149)
also gives this error

**Comment by Nikdo53** [comment]
Fixed in 1.4.2😎😎😎
