### ISSUE TITLE
Is it possible to make the mod compatible with NeoForge again?

### ISSUE THREAD

**Issue by Zedrimar** [AbraXator/MoreSnifferFlowers#12]
As of mod version 1.4.2, neoforge no longer compatible due to forge version bump to 47.2.0 (Neoforge latest is on 47.1.105, for MC 1.20.1). Is there any chance to have the mod compatible with neoforge again? If so that would be awesome!

**Comment by Nikdo53** [comment]
But they're compatible with each other tho, can't you just use forge instead? I really don't want to release another version so if you really want it I could probably just post it here

**Comment by Zedrimar** [comment]
Honestly, on any other day, I would agree with you and simply swap to forge. There is only one slight problem... Well, a problem for me anyway. I uh... I have 600 mods on my custom "little" pack.... Yes, you heard that right, that is no exaggeration.... Well, technically 4 mods short of 600, if going strictly by file count in my mods folder, rather than what (neo)forge shows when loaded (617 according to loading screen). Currently at 596 mods inside my mods folder. I just don't want to dig around to change every single Neoforge optimized port to forge, if I don't have to. There's quite a few to sort through in order to do that, even using AT Launcher....

On the bright side, as far as I can tell, the forge dependency number can just be changed down to some minimum for what neoforge also includes in their version numbers for 1.20.1. I loaded with neoforge 47.1.105 and it loaded up just fine after changing the dependency number in mods.TOML, inside the mod JAR file. Technically, next update that drops, could just be updated to have the minimum forge dependency number changed to a lower number, and it should work just fine.

I wanted to ask anyway, since I wasn't sure how deep any update(s) go, just in case there were method call updates that might have been updated specific to just forge or neoforge. I know that Neoforge has been made to be as interchangeable as possible for 1.20.1, but never know. Things can change quick. Neoforge has been picking up steam lately too. Although I personally haven't seen many (if any) mod authors say they are only supporting forge or neoforge and nothing else, I have definitely seen more and more authors start to move toward Neoforge more so than regular forge. At least as of late. Either due to ease of programming, issues with the head dev of original forge, or whatever. It was just easier for me to just move to neoforge now, rather than go through and do a sweep to change everything over later (when I might add even more mods).

I thankfully have enough basic knowledge of modding stuff that I can easily change the mods.toml file myself whenever I download the mod. Though obviously, it is a bit more convenient when the update can be centralized to the file upload, rather than having to tweak things every time a new update comes out. Plus, let's face it... Most people that download mods, either don't want to do that kind of tweaking, and or simply do not know how to. Not that it's even that hard to change when it comes down to it at the end of the day, but some people can barely even turn on a PC, let alone deal with code stuff. 

I guess all I am asking is just if it is possible to please have the next version update to have the mods.toml to have a lower forge minimum dependency number like 47.1.105 or something. That way neoforge is "supported" again, if at all possible. I don't need a separate update file myself at the moment, unless there are deeper mod changes/new or updated method calls in this mod, that break between neoforge and regular forge, which I am not aware of. If not, no big deal, just figured I'd ask.

**Comment by Nikdo53** [comment]
Alright, to be honest changing the forge version was done last minute cuz why not, we didn't know it would break stuff. I already reversed the change so once we make another minor update it'll be compatible again

**Comment by Zedrimar** [comment]
I was gonna respond earlier, but I got really sick... Just wanted to say thank you for the update, much appreciated!
