### ISSUE TITLE
Jar of bonemeal crash

### ISSUE THREAD

**Issue by Elnhomantia** [AbraXator/MoreSnifferFlowers#13]
If used in a "mixed" field, the jar of bonemeal will crash the game. 
![image](https://github.com/user-attachments/assets/84714d08-c197-4d2b-b627-86a5339f6bff)

Said "mixed field" :
![image](https://github.com/user-attachments/assets/63fad239-e6c1-4e30-b3aa-df8705750016)

**Comment by AbraXator** [comment]
Thanks for reporting this, it's fixed in the newest update.
