### ISSUE TITLE
Armor Trim and Trim Material Not Compatible With Modded Counterparts

### ISSUE THREAD

**Issue by Ghastly13** [AbraXator/MoreSnifferFlowers#6]
The Aroma Armor Trim and the Amber Shard material are not compatible with modded materials and modded trims. There are two ways to rectify this:
One method is with a mixin. You can see it in Alex's Caves here: https://github.com/AlexModGuy/AlexsCaves/blob/de4cd593deca46d5d06b82f932f098fd1a2cee9f/src/main/java/com/github/alexmodguy/alexscaves/mixin/client/SpriteResourceLoaderMixin.java#L25
This has the advantage of not requiring another mod.
Another method is using Trimmed:
https://modrinth.com/mod/trimmed
This is probably easier.
Also, the recipe for the Aroma Armor trim is bugged, it only produces one trim and not two.

**Comment by AbraXator** [comment]
Thanks for pointing this bug out, and for providing the solution too! It'll get fixed in the next update
